apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "logservice.hsc.philips.com.cn/v1",
          "kind": "LogProject",
          "metadata": {
            "name": "logproject-sample"
          },
          "spec": {
            "foo": "bar"
          }
        },
        {
          "apiVersion": "logservice.hsc.philips.com.cn/v1",
          "kind": "LogStore",
          "metadata": {
            "name": "logstore-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: alicloud-logservice-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: LogProject is the Schema for the logprojects API
      displayName: Log Project
      kind: LogProject
      name: logprojects.logservice.hsc.philips.com.cn
      version: v1
    - description: LogStore is the Schema for the logstores API
      displayName: Log Store
      kind: LogStore
      name: logstores.logservice.hsc.philips.com.cn
      version: v1
  description: Operator for AliCloud LogService
  displayName: alicloud-logservice-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - logservice.hsc.philips.com.cn
          resources:
          - logprojects
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - logservice.hsc.philips.com.cn
          resources:
          - logprojects/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - logservice.hsc.philips.com.cn
          resources:
          - logstores
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - logservice.hsc.philips.com.cn
          resources:
          - logstores/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: alicloud-logservice-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: leonjin/alicloud-logservice-operator:0.0.1
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - AliCloud LogService
  links:
  - name: Alicloud Logservice Operator
    url: https://alicloud-logservice-operator.domain
  maturity: alpha
  provider:
    name: HealthSuite China Team
  version: 0.0.1
