# permissions for end users to edit logstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logstore-editor-role
rules:
- apiGroups:
  - logservice.hsc.philips.com.cn
  resources:
  - logstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logservice.hsc.philips.com.cn
  resources:
  - logstores/status
  verbs:
  - get
